# Generated by Django 4.2.10 on 2024-03-23 04:54

from django.db import migrations, models

from apps.consultations.constants import DEFAULT_CONSULTATION_TEMPLATES


def remove_current_consultation_templates(apps, schema_editor):
    """Remove all current consultation templates."""
    ConsultationTemplate = apps.get_model("consultations", "ConsultationTemplate")
    ConsultationTemplate.objects.all().delete()


def create_default_consultation_templates(apps, schema_editor):
    """Remove all templates and create new default consultation templates."""
    ConsultationTemplate = apps.get_model("consultations", "ConsultationTemplate")
    ConsultationTemplate.objects.bulk_create(
        [
            ConsultationTemplate(
                session_type=template.session_type,
                duration=template.duration,
            ) for template in DEFAULT_CONSULTATION_TEMPLATES
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_note_consultationattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='template',
        ),
        migrations.RemoveField(
            model_name='consultationtemplate',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='consultationtemplate',
            name='fee',
        ),
        migrations.RunPython(
            remove_current_consultation_templates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='consultationtemplate',
            name='session_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('mentorship', 'Mentorship')], verbose_name='Session Type'),
        ),
        migrations.RunPython(
            create_default_consultation_templates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='Fee rate for consultation, max value is 1.', max_digits=10, verbose_name='Fee'),
        ),
    ]
