# Generated by Django 4.2.10 on 2024-03-25 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


def populate_user_consultaion_rates(apps, schema_editor):
    """Populate user consultation rates."""
    ConsultationRate = apps.get_model("consultations", "ConsultationRate")
    ConsultationTemplate = apps.get_model("consultations", "ConsultationTemplate")
    User = apps.get_model("users", "User")
    template_ids = ConsultationTemplate.objects.values_list("id", flat=True)
    user_rates = []
    for user in User.objects.all():
        user_rates.extend(
            [
                ConsultationRate(user_id=user.id, template_id=template_id)
                for template_id in template_ids
            ],
        )
    ConsultationRate.objects.bulk_create(user_rates)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0004_remove_consultation_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rate')),
                ('allow_offered', models.BooleanField(default=True, verbose_name='Allow Offered')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rates', to='consultations.consultationtemplate', verbose_name='Consultation Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Consultation Rate',
                'verbose_name_plural': 'Consultation Rates',
            },
        ),
        migrations.RunPython(
            populate_user_consultaion_rates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
