# Generated by Django 4.2.10 on 2024-04-23 07:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_completed_at'),
        ('payments', '0002_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('stripe_id', models.CharField(max_length=255, verbose_name='Stripe ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_session', to='consultations.consultation', verbose_name='Consultation')),
            ],
            options={
                'verbose_name': 'Stripe Checkout Session',
                'verbose_name_plural': 'Stripe Checkout Sessions',
            },
        ),
    ]
