# Generated by Django 4.2.10 on 2024-03-05 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


def populate_user_specialty_data(apps, schema_editor):
    """Populate user specialty data from string to list."""
    User = apps.get_model("users", "User")
    users = User.objects.all()
    for user in users:
        user.specialty_list = (
            user.specialty.split(",")
            if "," in user.specialty else user.specialty.split()
        )
    User.objects.bulk_update(users, fields=["specialty_list"])


def reverse_user_specialty_data(apps, schema_editor):
    """Reverse user specialty data from list to string."""
    User = apps.get_model("users", "User")
    users = User.objects.all()
    for user in users:
        user.specialty = ",".join(user.specialty)
    User.objects.bulk_update(users, fields=["specialty"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_city_user_clinician_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None, verbose_name='Specialty'),
        ),
        migrations.RunPython(
            populate_user_specialty_data,
            reverse_code=reverse_user_specialty_data,
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.AddField(
            model_name='user',
            name='specialty_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Specialty Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Decline reason'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='specialty_list',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
