# Generated by Django 4.2.10 on 2024-03-19 00:44

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_settings',
            field=models.JSONField(default=apps.users.utils.default_privacy_settings),
        ),
    ]
