# Generated by Django 4.2.10 on 2024-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_privacy_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinician_type',
            field=models.CharField(choices=[('crna', 'Certified Registered Nurse Anesthetists (CRNA)'), ('np', 'Nurse Practitioner (NP)'), ('pa', 'Physician Assistant (PA)'), ('pa_aa', 'Physician Assistant - Anesthesia Assistant (PA-AA)'), ('do', 'Physician: Doctor of Osteopathy (DO)'), ('md', 'Physician: Medical Doctor (MD)'), ('stu', 'Student/In-Training')], max_length=50, verbose_name='Clinician Type'),
        ),
    ]
