# Generated by Django 4.2.10 on 2024-04-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_clinician_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_notifications',
            field=models.BooleanField(default=False, verbose_name='Allow Notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, default='', verbose_name='Signature'),
        ),
    ]
