# Generated by Django 5.0.4 on 2024-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_state_remove_user_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinician_type',
            field=models.CharField(choices=[('crna', 'Certified Registered Nurse Anesthetist (CRNA)'), ('np', 'Nurse Practitioner (NP)'), ('pa', 'Physician Assistant (PA)'), ('pa_aa', 'Physician Assistant - Anesthesia Assistant (PA-AA)'), ('do', 'Physician: Doctor of Osteopathy (DO)'), ('md', 'Physician: Medical Doctor (MD)'), ('stu', 'Student/In-Training')], max_length=50, verbose_name='Clinician Type'),
        ),
    ]
