# Generated by Django 5.0.4 on 2024-04-22 07:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_clinician_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=3, verbose_name='Specialty'),
        ),
    ]
