# Generated by Django 5.0.4 on 2024-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_address_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=models.CharField(blank=True, max_length=255, verbose_name='Credentials'),
        ),
    ]
